export const locales = ["en", "tr", "es", "de", "fr", "ja", "ar"] as const;
export type Locale = (typeof locales)[number];

export const localeNames: Record<Locale, string> = {
  en: "English", tr: "Türkçe", es: "Español", de: "Deutsch",
  fr: "Français", ja: "日本語", ar: "العربية",
};

export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);

type Copy = {
  dir: "ltr" | "rtl";
  metaTitle: string;
  metaDescription: string;
  nav: { overview: string; intelligence: string; languages: string; trust: string };
  appLogin: string;
  walkthrough: string;
  hero: { eyebrow: string; title: string; body: string; explore: string; proof: string[] };
  model: { know: string; move: string; prove: string };
  brand: { eyebrow: string; title: string; body: string; principles: Array<[string, string, string]> };
  flow: { eyebrow: string; title: string; body: string; steps: Array<[string, string]> };
  ai: { eyebrow: string; title: string; body: string; fieldRole: string; fieldQuestion: string; fieldAnswer: string; managerRole: string; managerQuestion: string; managerAnswer: string; close: string };
  language: { eyebrow: string; title: string; body: string; available: string; preparing: string; note: string };
  trust: { eyebrow: string; title: string; body: string; points: Array<[string, string]> };
  final: { eyebrow: string; title: string; body: string; button: string };
  footer: string;
};

export const copy: Record<Locale, Copy> = {
  en: {
    dir: "ltr", metaTitle: "QANRI | Operational Intelligence Platform", metaDescription: "QANRI connects field execution, company knowledge, evidence, review and AI-assisted decisions in one trusted operating record.",
    nav: { overview: "Overview", intelligence: "Intelligence", languages: "Languages", trust: "Trust" }, appLogin: "App Login", walkthrough: "Book a walkthrough",
    hero: { eyebrow: "OPERATIONAL INTELLIGENCE PLATFORM", title: "The intelligence between work and proof.", body: "QANRI connects people, field execution, company knowledge and evidence in one operational system.", explore: "Explore the operating model", proof: ["Work stays connected to its owner", "Evidence remains tied to the record", "Company knowledge becomes usable in the field"] },
    model: { know: "See the operation as it actually happened.", move: "Direct the right person and next action.", prove: "Verify the work through history and evidence." },
    brand: { eyebrow: "WHAT QANRI MEANS", title: "The name defines the operating standard.", body: "QANRI is formed from five operating principles. They are not decorative values; together they describe how work becomes knowledge, action and proof.", principles: [["Q","Quality","Make the standard of work visible and measurable."],["A","Accountability","Keep responsibility, time and evidence connected."],["N","Navigation","Turn the operating record into the right next action."],["R","Reliability","Preserve field reality with its history intact."],["I","Intelligence","Transform operational activity into knowledge the company can use."]] },
    flow: { eyebrow: "ONE OPERATION, END TO END", title: "Work becomes operational knowledge.", body: "Every assignment, question, blocker, submission and decision adds context to the same trusted record.", steps: [["Assign", "Define the work, owner and required evidence."], ["Execute", "Guide the team where the work happens."], ["Ask", "Use company knowledge in the context of the job."], ["Verify", "Review evidence without losing history."], ["Act", "See risk and direct the next decision."]] },
    ai: { eyebrow: "A COMPANY-SPECIFIC OPERATIONAL BRAIN", title: "Every person can ask. The operation can answer.", body: "Ask QANRI places an AI assistant beside the people doing the work and the people directing it. Answers begin with authorized company knowledge and live operational context.", fieldRole: "A technician in the field asks", fieldQuestion: "How should this assembly be completed?", fieldAnswer: "QANRI brings the relevant procedure, project context and recorded work into one guided answer.", managerRole: "A manager asks", managerQuestion: "What is at risk right now, and who owns the next action?", managerAnswer: "QANRI reads assignments, blockers, evidence and review status to build an operational answer.", close: "One intelligence layer. Different questions. The same operational truth." },
    language: { eyebrow: "PRODUCT LANGUAGE STATUS", title: "Global by design. Honest about availability.", body: "This website is available in seven languages. Product interface availability is shown separately so the promise always matches the experience.", available: "Available", preparing: "In preparation", note: "English and Turkish are currently available in the QANRI application. Additional product languages are being prepared and are not presented as fully available." },
    trust: { eyebrow: "TRUSTED BY DESIGN", title: "Intelligence begins with operational truth.", body: "QANRI keeps responsibility, time, evidence, access and history connected so important answers can be traced back to the work.", points: [["Authorized knowledge", "AI begins with sources the company permits."], ["Traceable answers", "Recorded fact remains distinct from interpretation."], ["Human judgment", "Accountable decisions remain with people."]] },
    final: { eyebrow: "KNOW. MOVE. PROVE.", title: "Bring us one real operation.", body: "Show us how work moves today. See how QANRI turns it into an operational record your company can understand and act on.", button: "Book a walkthrough" }, footer: "Operational intelligence for verifiable operations."
  },
  tr: {
    dir: "ltr", metaTitle: "QANRI | Operasyonel Zekâ Platformu", metaDescription: "Saha faaliyetini kurumsal bilgiye, karara ve doğrulanabilir kanıta dönüştürün.",
    nav: { overview: "Genel Bakış", intelligence: "Operasyonel Zekâ", languages: "Diller", trust: "Güven" }, appLogin: "Giriş", walkthrough: "Ürün sunumu planla",
    hero: { eyebrow: "OPERASYONEL ZEKÂ PLATFORMU", title: "İş ile kanıt arasındaki zekâ.", body: "QANRI; insanları, saha uygulamasını, şirket bilgisini ve kanıtı tek bir operasyonel sistemde birleştirir.", explore: "Çalışma modelini incele", proof: ["İş, sorumlusuyla bağlantılı kalır", "Kanıt, operasyon kaydından ayrılmaz", "Şirket bilgisi sahada kullanılabilir hale gelir"] },
    model: { know: "Operasyonu gerçekten yaşandığı biçimde görün.", move: "Doğru kişiyi ve sonraki adımı yönlendirin.", prove: "İşi geçmişi ve kanıtıyla doğrulayın." },
    brand: { eyebrow: "QANRI NE ANLAMA GELİYOR?", title: "İsmi, çalışma standardını tanımlar.", body: "QANRI adı beş İngilizce çalışma ilkesinin baş harflerinden oluşur. Türkçede bu ilkeler; kalite, hesap verebilirlik, doğru yönlendirme, güvenilirlik ve zekâ anlamına gelir.", principles: [["Q","Quality · Kalite","Yapılan işin standardını görünür ve ölçülebilir kılmak."],["A","Accountability · Hesap verebilirlik","Sorumluluğu, zamanı ve kanıtı aynı kayıtta tutmak."],["N","Navigation · Doğru yönlendirme","Operasyon kaydını doğru sonraki adıma dönüştürmek."],["R","Reliability · Güvenilirlik","Saha gerçeğini geçmişiyle birlikte korumak."],["I","Intelligence · Zekâ","Operasyon faaliyetini şirketin kullanabileceği bilgiye dönüştürmek."]] },
    flow: { eyebrow: "UÇTAN UCA TEK OPERASYON", title: "Yapılan iş, operasyonel bilgiye dönüşür.", body: "Her görev, soru, engel, gönderim ve karar aynı güvenilir operasyon kaydına bağlam ekler.", steps: [["Görevlendir", "İşi, sorumluyu ve gerekli kanıtı tanımlayın."], ["Uygula", "Ekibi işin gerçekleştiği yerde yönlendirin."], ["Sor", "Şirket bilgisini işin bağlamında kullanın."], ["Doğrula", "Geçmişi kaybetmeden kanıtı inceleyin."], ["Harekete geç", "Riski görün ve sonraki kararı yönlendirin."]] },
    ai: { eyebrow: "ŞİRKETE ÖZEL OPERASYONEL BEYİN", title: "Herkes sorabilir. Operasyon cevap verebilir.", body: "Ask QANRI, işi yapanların ve yönetenlerin yanına bir yapay zekâ yardımcısı yerleştirir. Yanıtlar yetkilendirilmiş şirket bilgisi ve canlı operasyon bağlamından başlar.", fieldRole: "Sahadaki teknisyen sorar", fieldQuestion: "Bu montajı nasıl tamamlamalıyım?", fieldAnswer: "QANRI ilgili prosedürü, proje bağlamını ve kayıtlı işi tek bir yönlendirici yanıtta bir araya getirir.", managerRole: "Yönetici sorar", managerQuestion: "Şu anda risk altında olan ne ve sonraki adım kimde?", managerAnswer: "QANRI; görevleri, engelleri, kanıtları ve inceleme durumunu okuyarak operasyonel yanıt oluşturur.", close: "Tek zekâ katmanı. Farklı sorular. Aynı operasyonel gerçek." },
    language: { eyebrow: "ÜRÜN DİL DURUMU", title: "Tasarımı küresel. Kullanılabilirliği şeffaf.", body: "Bu web sitesi yedi dilde kullanılabilir. Verilen sözün ürün deneyimiyle örtüşmesi için uygulama arayüzü dilleri ayrıca gösterilir.", available: "Kullanılabilir", preparing: "Hazırlanıyor", note: "QANRI uygulaması şu anda İngilizce ve Türkçe kullanılabilir. Diğer ürün dilleri hazırlanmaktadır ve tamamlanmış olarak sunulmamaktadır." },
    trust: { eyebrow: "GÜVEN TEMELİYLE TASARLANDI", title: "Zekâ, operasyonel gerçekle başlar.", body: "QANRI; sorumluluk, zaman, kanıt, erişim ve geçmişi birbirine bağlı tutar. Böylece önemli yanıtlar yapılan işe kadar izlenebilir.", points: [["Yetkili bilgi", "Yapay zekâ şirketin izin verdiği kaynaklardan başlar."], ["İzlenebilir yanıt", "Kayıtlı gerçek, yorumdan ayrı tutulur."], ["İnsan kararı", "Hesap verebilir kararlar insanlarda kalır."]] },
    final: { eyebrow: "BİL. HAREKETE GEÇ. KANITLA.", title: "Bize gerçek bir operasyon getirin.", body: "İşin bugün nasıl ilerlediğini gösterin. QANRI’nin bunu şirketinizin anlayıp harekete geçebileceği bir operasyon kaydına nasıl dönüştürdüğünü görün.", button: "Ürün sunumu planla" }, footer: "Doğrulanabilir operasyonlar için operasyonel zekâ."
  },
  es: {
    dir: "ltr", metaTitle: "QANRI | Plataforma de inteligencia operativa", metaDescription: "Convierta la actividad de campo en conocimiento, decisiones y evidencia verificable.",
    nav: { overview: "Visión general", intelligence: "Inteligencia", languages: "Idiomas", trust: "Confianza" }, appLogin: "Acceder", walkthrough: "Solicitar una demostración",
    hero: { eyebrow: "PLATAFORMA DE INTELIGENCIA OPERATIVA", title: "La inteligencia entre el trabajo y la evidencia.", body: "QANRI conecta personas, ejecución en campo, conocimiento de la empresa y evidencia en un solo sistema operativo.", explore: "Explorar el modelo operativo", proof: ["El trabajo permanece conectado con su responsable", "La evidencia permanece vinculada al registro", "El conocimiento de la empresa llega al campo"] },
    model: { know: "Vea la operación tal como ocurrió.", move: "Dirija a la persona y la próxima acción correctas.", prove: "Verifique el trabajo mediante historial y evidencia." },
    brand: { eyebrow: "QUÉ SIGNIFICA QANRI", title: "El nombre define una forma de operar.", body: "QANRI nace de las iniciales de cinco principios operativos en inglés. En español expresan calidad, responsabilidad, orientación, confiabilidad e inteligencia.", principles: [["Q","Quality · Calidad","Hacer visible y medible el estándar del trabajo."],["A","Accountability · Responsabilidad","Mantener unidos al responsable, el momento y la evidencia."],["N","Navigation · Orientación","Convertir el registro operativo en la próxima acción correcta."],["R","Reliability · Confiabilidad","Conservar la realidad del campo y todo su historial."],["I","Intelligence · Inteligencia","Transformar la actividad en conocimiento útil para la empresa."]] },
    flow: { eyebrow: "UNA OPERACIÓN DE PRINCIPIO A FIN", title: "El trabajo se convierte en conocimiento operativo.", body: "Cada tarea, pregunta, bloqueo, entrega y decisión añade contexto al mismo registro confiable.", steps: [["Asignar", "Defina el trabajo, el responsable y la evidencia requerida."], ["Ejecutar", "Guíe al equipo donde ocurre el trabajo."], ["Preguntar", "Utilice el conocimiento de la empresa en el contexto del trabajo."], ["Verificar", "Revise la evidencia sin perder el historial."], ["Actuar", "Detecte el riesgo y dirija la siguiente decisión."]] },
    ai: { eyebrow: "UN CEREBRO OPERATIVO ESPECÍFICO PARA SU EMPRESA", title: "Todos pueden preguntar. La operación puede responder.", body: "Ask QANRI acompaña con un asistente de IA tanto a quienes realizan el trabajo como a quienes lo dirigen. Las respuestas parten del conocimiento autorizado de la empresa y del contexto operativo en tiempo real.", fieldRole: "Un técnico en campo pregunta", fieldQuestion: "¿Cómo debo completar este montaje?", fieldAnswer: "QANRI reúne el procedimiento pertinente, el contexto del proyecto y el trabajo registrado en una respuesta guiada.", managerRole: "Un responsable pregunta", managerQuestion: "¿Qué está en riesgo ahora y quién tiene la próxima acción?", managerAnswer: "QANRI analiza tareas, bloqueos, evidencia y revisiones para construir una respuesta operativa.", close: "Una capa de inteligencia. Preguntas diferentes. La misma verdad operativa." },
    language: { eyebrow: "ESTADO DE IDIOMAS DEL PRODUCTO", title: "Global por diseño. Transparente sobre su disponibilidad.", body: "Este sitio web está disponible en siete idiomas. Los idiomas de la aplicación se muestran por separado para que la promesa coincida con la experiencia.", available: "Disponible", preparing: "En preparación", note: "La aplicación QANRI está disponible actualmente en inglés y turco. Los demás idiomas del producto están en preparación y no se presentan como totalmente disponibles." },
    trust: { eyebrow: "CONFIANZA POR DISEÑO", title: "La inteligencia comienza con la verdad operativa.", body: "QANRI conecta responsabilidad, tiempo, evidencia, acceso e historial para que cada respuesta importante pueda rastrearse hasta el trabajo.", points: [["Conocimiento autorizado", "La IA parte de las fuentes permitidas por la empresa."], ["Respuestas trazables", "Los hechos registrados se distinguen de la interpretación."], ["Juicio humano", "Las decisiones responsables permanecen en manos de las personas."]] },
    final: { eyebrow: "CONOCE. AVANZA. DEMUESTRA.", title: "Tráiganos una operación real.", body: "Muéstrenos cómo se mueve hoy el trabajo. Vea cómo QANRI lo convierte en un registro que su empresa puede comprender y utilizar.", button: "Solicitar una demostración" }, footer: "Inteligencia operativa para operaciones verificables."
  },
  de: {
    dir: "ltr", metaTitle: "QANRI | Plattform für operative Intelligenz", metaDescription: "Machen Sie aus Feldarbeit Unternehmenswissen, klare Entscheidungen und nachweisbare Ergebnisse.",
    nav: { overview: "Überblick", intelligence: "Intelligenz", languages: "Sprachen", trust: "Vertrauen" }, appLogin: "Anmelden", walkthrough: "Produktdemo vereinbaren",
    hero: { eyebrow: "PLATTFORM FÜR OPERATIVE INTELLIGENZ", title: "Die Intelligenz zwischen Arbeit und Nachweis.", body: "QANRI verbindet Menschen, Feldausführung, Unternehmenswissen und Nachweise in einem operativen System.", explore: "Betriebsmodell ansehen", proof: ["Arbeit bleibt mit der verantwortlichen Person verbunden", "Nachweise bleiben dem Vorgang zugeordnet", "Unternehmenswissen wird im Feld nutzbar"] },
    model: { know: "Sehen Sie den Betrieb so, wie er tatsächlich ablief.", move: "Steuern Sie die richtige Person und den nächsten Schritt.", prove: "Prüfen Sie die Arbeit anhand von Verlauf und Nachweisen." },
    brand: { eyebrow: "WOFÜR QANRI STEHT", title: "Der Name beschreibt den operativen Anspruch.", body: "QANRI setzt sich aus den Anfangsbuchstaben von fünf englischen Leitprinzipien zusammen. Auf Deutsch stehen sie für Qualität, Verantwortlichkeit, Orientierung, Zuverlässigkeit und Intelligenz.", principles: [["Q","Quality · Qualität","Arbeitsstandards sichtbar und messbar machen."],["A","Accountability · Verantwortlichkeit","Verantwortung, Zeitpunkt und Nachweis verbunden halten."],["N","Navigation · Orientierung","Aus dem Betriebsdatensatz den richtigen nächsten Schritt ableiten."],["R","Reliability · Zuverlässigkeit","Die Realität im Feld mit ihrem vollständigen Verlauf bewahren."],["I","Intelligence · Intelligenz","Operative Aktivität in nutzbares Unternehmenswissen verwandeln."]] },
    flow: { eyebrow: "EIN VORGANG, DURCHGÄNGIG VERBUNDEN", title: "Arbeit wird zu operativem Wissen.", body: "Jeder Auftrag, jede Frage, Blockade, Einreichung und Entscheidung ergänzt denselben verlässlichen Datensatz.", steps: [["Zuweisen", "Definieren Sie Arbeit, Verantwortung und erforderliche Nachweise."], ["Ausführen", "Unterstützen Sie das Team direkt am Einsatzort."], ["Fragen", "Nutzen Sie Unternehmenswissen im Kontext des Auftrags."], ["Prüfen", "Bewerten Sie Nachweise, ohne den Verlauf zu verlieren."], ["Handeln", "Erkennen Sie Risiken und steuern Sie die nächste Entscheidung."]] },
    ai: { eyebrow: "EIN UNTERNEHMENSSPEZIFISCHES OPERATIVES GEHIRN", title: "Jeder kann fragen. Der Betrieb kann antworten.", body: "Ask QANRI stellt den ausführenden und steuernden Personen einen KI-Assistenten zur Seite. Antworten beginnen mit autorisiertem Unternehmenswissen und aktuellem Betriebskontext.", fieldRole: "Eine Fachkraft im Feld fragt", fieldQuestion: "Wie soll ich diese Montage abschließen?", fieldAnswer: "QANRI führt die passende Anweisung, den Projektkontext und die dokumentierte Arbeit in einer geführten Antwort zusammen.", managerRole: "Eine Führungskraft fragt", managerQuestion: "Was ist aktuell gefährdet und wer verantwortet den nächsten Schritt?", managerAnswer: "QANRI wertet Aufgaben, Blockaden, Nachweise und Prüfstatus für eine operative Antwort aus.", close: "Eine Intelligenzschicht. Unterschiedliche Fragen. Dieselbe operative Wahrheit." },
    language: { eyebrow: "SPRACHSTATUS DES PRODUKTS", title: "Global konzipiert. Transparent verfügbar.", body: "Diese Website ist in sieben Sprachen verfügbar. Die Sprachen der Anwendung werden separat ausgewiesen, damit Versprechen und Produkterlebnis übereinstimmen.", available: "Verfügbar", preparing: "In Vorbereitung", note: "Die QANRI-Anwendung ist derzeit auf Englisch und Türkisch verfügbar. Weitere Produktsprachen werden vorbereitet und nicht als vollständig verfügbar dargestellt." },
    trust: { eyebrow: "VERTRAUEN ALS DESIGNPRINZIP", title: "Intelligenz beginnt mit operativer Wahrheit.", body: "QANRI verbindet Verantwortung, Zeit, Nachweise, Zugriffe und Verlauf, damit wichtige Antworten bis zur ausgeführten Arbeit zurückverfolgt werden können.", points: [["Autorisiertes Wissen", "Die KI beginnt mit vom Unternehmen freigegebenen Quellen."], ["Nachvollziehbare Antworten", "Dokumentierte Fakten bleiben von Interpretationen getrennt."], ["Menschliche Entscheidung", "Verantwortliche Entscheidungen bleiben beim Menschen."]] },
    final: { eyebrow: "WISSEN. BEWEGEN. BELEGEN.", title: "Bringen Sie uns einen realen Betriebsablauf.", body: "Zeigen Sie uns, wie Ihre Arbeit heute abläuft. Erleben Sie, wie QANRI daraus einen Datensatz macht, den Ihr Unternehmen verstehen und nutzen kann.", button: "Produktdemo vereinbaren" }, footer: "Operative Intelligenz für nachweisbare Abläufe."
  },
  fr: {
    dir: "ltr", metaTitle: "QANRI | Plateforme d’intelligence opérationnelle", metaDescription: "Transformez l’activité terrain en connaissance, en décision et en preuve vérifiable.",
    nav: { overview: "Vue d’ensemble", intelligence: "Intelligence", languages: "Langues", trust: "Confiance" }, appLogin: "Connexion", walkthrough: "Réserver une démonstration",
    hero: { eyebrow: "PLATEFORME D’INTELLIGENCE OPÉRATIONNELLE", title: "L’intelligence entre le travail et la preuve.", body: "QANRI relie les personnes, l’exécution terrain, le savoir de l’entreprise et les preuves dans un même système opérationnel.", explore: "Découvrir le modèle opérationnel", proof: ["Le travail reste lié à son responsable", "La preuve reste attachée au dossier", "Le savoir de l’entreprise devient utilisable sur le terrain"] },
    model: { know: "Voyez l’opération telle qu’elle s’est réellement déroulée.", move: "Orientez la bonne personne et la prochaine action.", prove: "Vérifiez le travail par l’historique et les preuves." },
    brand: { eyebrow: "CE QUE SIGNIFIE QANRI", title: "Le nom définit une exigence opérationnelle.", body: "QANRI réunit les initiales de cinq principes opérationnels en anglais. En français, ils expriment la qualité, la responsabilité, l’orientation, la fiabilité et l’intelligence.", principles: [["Q","Quality · Qualité","Rendre le niveau de travail visible et mesurable."],["A","Accountability · Responsabilité","Relier le responsable, le moment et la preuve."],["N","Navigation · Orientation","Transformer le dossier opérationnel en prochaine action pertinente."],["R","Reliability · Fiabilité","Préserver la réalité du terrain et son historique."],["I","Intelligence · Intelligence","Transformer l’activité en connaissance utile à l’entreprise."]] },
    flow: { eyebrow: "UNE OPÉRATION DE BOUT EN BOUT", title: "Le travail devient une connaissance opérationnelle.", body: "Chaque mission, question, blocage, soumission et décision enrichit le même dossier fiable.", steps: [["Attribuer", "Définissez le travail, le responsable et les preuves requises."], ["Exécuter", "Guidez l’équipe là où le travail a lieu."], ["Demander", "Utilisez le savoir de l’entreprise dans le contexte du travail."], ["Vérifier", "Examinez les preuves sans perdre l’historique."], ["Agir", "Identifiez le risque et dirigez la prochaine décision."]] },
    ai: { eyebrow: "UN CERVEAU OPÉRATIONNEL PROPRE À L’ENTREPRISE", title: "Chacun peut demander. L’opération peut répondre.", body: "Ask QANRI place un assistant IA auprès de ceux qui réalisent le travail et de ceux qui le dirigent. Les réponses partent du savoir autorisé de l’entreprise et du contexte opérationnel en temps réel.", fieldRole: "Un technicien sur le terrain demande", fieldQuestion: "Comment dois-je terminer ce montage ?", fieldAnswer: "QANRI rassemble la procédure pertinente, le contexte du projet et le travail enregistré dans une réponse guidée.", managerRole: "Un responsable demande", managerQuestion: "Qu’est-ce qui est à risque maintenant et qui porte la prochaine action ?", managerAnswer: "QANRI analyse les missions, blocages, preuves et statuts de validation pour produire une réponse opérationnelle.", close: "Une couche d’intelligence. Des questions différentes. Une même vérité opérationnelle." },
    language: { eyebrow: "ÉTAT DES LANGUES DU PRODUIT", title: "Mondial par conception. Transparent sur la disponibilité.", body: "Ce site est disponible en sept langues. Les langues de l’application sont indiquées séparément afin que la promesse corresponde à l’expérience.", available: "Disponible", preparing: "En préparation", note: "L’application QANRI est actuellement disponible en anglais et en turc. Les autres langues du produit sont en préparation et ne sont pas présentées comme entièrement disponibles." },
    trust: { eyebrow: "LA CONFIANCE PAR CONCEPTION", title: "L’intelligence commence par la vérité opérationnelle.", body: "QANRI relie responsabilité, temps, preuves, accès et historique afin que chaque réponse importante puisse être retracée jusqu’au travail.", points: [["Savoir autorisé", "L’IA part des sources approuvées par l’entreprise."], ["Réponses traçables", "Les faits enregistrés restent distincts de l’interprétation."], ["Jugement humain", "Les décisions responsables restent humaines."]] },
    final: { eyebrow: "SAVOIR. AGIR. PROUVER.", title: "Présentez-nous une opération réelle.", body: "Montrez-nous comment le travail avance aujourd’hui. Découvrez comment QANRI le transforme en un dossier que votre entreprise peut comprendre et exploiter.", button: "Réserver une démonstration" }, footer: "L’intelligence opérationnelle au service d’opérations vérifiables."
  },
  ja: {
    dir: "ltr", metaTitle: "QANRI | オペレーショナルインテリジェンス・プラットフォーム", metaDescription: "現場活動を企業知識、的確な判断、検証可能な証拠へ変換します。",
    nav: { overview: "概要", intelligence: "オペレーショナルAI", languages: "言語", trust: "信頼性" }, appLogin: "ログイン", walkthrough: "製品デモを予約",
    hero: { eyebrow: "オペレーショナルインテリジェンス・プラットフォーム", title: "作業と証明をつなぐ知性。", body: "QANRIは、人、現場作業、企業知識、証拠を一つの運用システムで結びます。", explore: "運用モデルを見る", proof: ["作業と担当者の関係を維持", "証拠を作業記録に保持", "企業知識を現場で活用"] },
    model: { know: "実際に起きた運用を正確に把握します。", move: "適切な担当者と次の行動を導きます。", prove: "履歴と証拠によって作業を検証します。" },
    brand: { eyebrow: "QANRIという名前に込めた意味", title: "五つの原則が、運用の基準になる。", body: "QANRIは、英語で表した五つの運用原則の頭文字から生まれた名称です。日本語では、品質、説明責任、次の行動への導き、信頼性、そして知性を意味します。", principles: [["Q","Quality · 品質","仕事の基準を見える形にし、測定できる状態にする。"],["A","Accountability · 説明責任","誰が、いつ、どの証拠とともに行ったかを明確にする。"],["N","Navigation · 導き","運用記録から、取るべき次の行動を示す。"],["R","Reliability · 信頼性","現場の事実とその履歴を失わずに守る。"],["I","Intelligence · 知性","日々の活動を、企業が活用できる知識へ変える。"]] },
    flow: { eyebrow: "一つの運用を最初から最後まで", title: "作業が運用知識へ変わる。", body: "割り当て、質問、障害、提出、判断のすべてが、同じ信頼できる記録に文脈を加えます。", steps: [["割り当て", "作業、担当者、必要な証拠を定義します。"], ["実行", "作業が行われる場所でチームを支援します。"], ["質問", "作業の文脈で企業知識を活用します。"], ["検証", "履歴を失わずに証拠を確認します。"], ["行動", "リスクを把握し、次の判断を導きます。"]] },
    ai: { eyebrow: "企業専用の運用頭脳", title: "誰もが質問できる。運用が答えられる。", body: "Ask QANRIは、作業する人と指揮する人のそばにAIアシスタントを配置します。回答は、許可された企業知識と現在の運用状況に基づきます。", fieldRole: "現場の技術者が質問", fieldQuestion: "この組立作業はどのように完了すべきですか？", fieldAnswer: "QANRIは、関連手順、プロジェクトの状況、記録済みの作業を一つのガイド付き回答にまとめます。", managerRole: "管理者が質問", managerQuestion: "今、何がリスクにさらされ、次の対応は誰の担当ですか？", managerAnswer: "QANRIは、タスク、障害、証拠、承認状況を読み取り、運用上の回答を構築します。", close: "一つの知能レイヤー。異なる質問。同じ運用上の事実。" },
    language: { eyebrow: "製品の言語対応状況", title: "グローバルな設計。誠実な対応表示。", body: "このウェブサイトは7言語で利用できます。製品体験との一貫性を保つため、アプリの対応言語は別に表示します。", available: "利用可能", preparing: "準備中", note: "QANRIアプリは現在、英語とトルコ語に対応しています。その他の製品言語は準備中であり、完全対応として案内していません。" },
    trust: { eyebrow: "信頼を前提とした設計", title: "知性は運用上の事実から始まる。", body: "QANRIは責任、時間、証拠、アクセス、履歴を結び、重要な回答を実際の作業まで追跡できるようにします。", points: [["許可された知識", "AIは企業が許可した情報源から始めます。"], ["追跡可能な回答", "記録された事実と解釈を区別します。"], ["人による判断", "説明責任を伴う決定は人が行います。"]] },
    final: { eyebrow: "KNOW. MOVE. PROVE.", title: "実際の運用を一つお聞かせください。", body: "現在の作業の流れをお見せください。QANRIがそれを、企業が理解し行動できる運用記録へ変える方法をご紹介します。", button: "製品デモを予約" }, footer: "検証可能な運用のためのオペレーショナルインテリジェンス。"
  },
  ar: {
    dir: "rtl", metaTitle: "QANRI | منصة الذكاء التشغيلي", metaDescription: "حوّل نشاط الميدان إلى معرفة مؤسسية وقرارات واضحة وإثبات قابل للتحقق.",
    nav: { overview: "نظرة عامة", intelligence: "الذكاء التشغيلي", languages: "اللغات", trust: "الثقة" }, appLogin: "دخول", walkthrough: "احجز عرضاً توضيحياً",
    hero: { eyebrow: "منصة الذكاء التشغيلي", title: "الذكاء بين العمل والإثبات.", body: "يربط QANRI الأشخاص والتنفيذ الميداني ومعرفة الشركة والأدلة ضمن نظام تشغيلي واحد.", explore: "استكشف نموذج التشغيل", proof: ["يبقى العمل مرتبطاً بالمسؤول عنه", "تبقى الأدلة مرتبطة بالسجل", "تصبح معرفة الشركة متاحة في الميدان"] },
    model: { know: "شاهد العملية كما حدثت فعلاً.", move: "وجّه الشخص المناسب والخطوة التالية.", prove: "تحقق من العمل من خلال السجل والأدلة." },
    brand: { eyebrow: "المعنى الذي يحمله اسم QANRI", title: "خمسة مبادئ تحدد معيار التشغيل.", body: "يتكوّن اسم QANRI من الأحرف الأولى لخمسة مبادئ تشغيلية باللغة الإنجليزية. وهي تعبّر بالعربية عن الجودة والمساءلة والتوجيه والموثوقية والذكاء.", principles: [["Q","Quality · الجودة","جعل معيار العمل واضحاً وقابلاً للقياس."],["A","Accountability · المساءلة","ربط المسؤول والوقت والدليل بالعمل نفسه."],["N","Navigation · التوجيه","تحويل السجل التشغيلي إلى الخطوة التالية الصحيحة."],["R","Reliability · الموثوقية","حفظ حقيقة الميدان مع سجلها الكامل."],["I","Intelligence · الذكاء","تحويل النشاط التشغيلي إلى معرفة تستفيد منها الشركة."]] },
    flow: { eyebrow: "عملية واحدة من البداية إلى النهاية", title: "يتحول العمل إلى معرفة تشغيلية.", body: "تضيف كل مهمة وسؤال وعائق وتسليم وقرار سياقاً إلى السجل الموثوق نفسه.", steps: [["التكليف", "حدد العمل والمسؤول والأدلة المطلوبة."], ["التنفيذ", "وجّه الفريق في موقع العمل."], ["السؤال", "استخدم معرفة الشركة ضمن سياق المهمة."], ["التحقق", "راجع الأدلة من دون فقدان السجل."], ["اتخاذ الإجراء", "حدد المخاطر ووجّه القرار التالي."]] },
    ai: { eyebrow: "عقل تشغيلي مخصص لشركتك", title: "يمكن للجميع أن يسألوا. ويمكن للعملية أن تجيب.", body: "يضع Ask QANRI مساعداً بالذكاء الاصطناعي إلى جانب من ينفذون العمل ومن يديرونه. تبدأ الإجابات من معرفة الشركة المصرح بها والسياق التشغيلي المباشر.", fieldRole: "يسأل فني في الميدان", fieldQuestion: "كيف ينبغي إكمال هذا التركيب؟", fieldAnswer: "يجمع QANRI الإجراء المناسب وسياق المشروع والعمل المسجل في إجابة إرشادية واحدة.", managerRole: "يسأل المدير", managerQuestion: "ما المعرض للخطر الآن، ومن يملك الخطوة التالية؟", managerAnswer: "يقرأ QANRI المهام والعوائق والأدلة وحالة المراجعة ليكوّن إجابة تشغيلية.", close: "طبقة ذكاء واحدة. أسئلة مختلفة. حقيقة تشغيلية واحدة." },
    language: { eyebrow: "حالة لغات المنتج", title: "مصمم للعالم. واضح بشأن التوفر.", body: "يتوفر هذا الموقع بسبع لغات. وتُعرض لغات واجهة التطبيق بصورة منفصلة حتى تتطابق الوعود مع تجربة المنتج.", available: "متوفر", preparing: "قيد الإعداد", note: "يتوفر تطبيق QANRI حالياً باللغتين الإنجليزية والتركية. أما لغات المنتج الأخرى فهي قيد الإعداد ولا يتم تقديمها على أنها متاحة بالكامل." },
    trust: { eyebrow: "الثقة جزء من التصميم", title: "يبدأ الذكاء من الحقيقة التشغيلية.", body: "يربط QANRI المسؤولية والوقت والأدلة والصلاحيات والسجل بحيث يمكن تتبع كل إجابة مهمة إلى العمل نفسه.", points: [["معرفة مصرح بها", "يبدأ الذكاء الاصطناعي من المصادر التي تسمح بها الشركة."], ["إجابات قابلة للتتبع", "تبقى الحقائق المسجلة منفصلة عن التفسير."], ["الحكم البشري", "تبقى القرارات المسؤولة بيد الأشخاص."]] },
    final: { eyebrow: "اعرف. تحرك. أثبت.", title: "قدّم لنا عملية حقيقية واحدة.", body: "أرنا كيف يتحرك العمل اليوم. واكتشف كيف يحوله QANRI إلى سجل تشغيلي تستطيع شركتك فهمه والعمل بناءً عليه.", button: "احجز عرضاً توضيحياً" }, footer: "ذكاء تشغيلي لعمليات قابلة للتحقق."
  }
};

export const productLanguages = [
  { locale: "en" as Locale, status: "available" },
  { locale: "tr" as Locale, status: "available" },
  { locale: "es" as Locale, status: "preparing" },
  { locale: "de" as Locale, status: "preparing" },
  { locale: "fr" as Locale, status: "preparing" },
  { locale: "ja" as Locale, status: "preparing" },
  { locale: "ar" as Locale, status: "preparing" },
] as const;
