import Image from "next/image";
import Link from "next/link";
import { APP_URL } from "./site-config";
import { copy, localeNames, productLanguages, type Locale } from "./i18n";
import { depthCopy } from "./i18n-depth";
import { parityCopy } from "./i18n-parity";
import { LanguageMenu } from "./language-menu";
import { LocalizedProductTour } from "./localized-product-tour";
import { DocumentLocale } from "./document-locale";

export function LocalizedHome({locale}:{locale:Locale}){const t=copy[locale],d=depthCopy[locale],p=parityCopy[locale];const questions=[...d.questions.items,p.fifthQuestion];const comparisons=[...d.comparison.rows,p.comparisonFifth];return <div className="localized-site" lang={locale} dir={t.dir}><DocumentLocale locale={locale} dir={t.dir}/>
  <header className="nav localized-nav"><Link className="brand-lockup" href={locale === "en" ? "/" : `/${locale}`} aria-label="QANRI home"><Image src="/qanri/QANRI_Web_Lockup_Transparent.png" width={1141} height={304} alt="QANRI. Know. Move. Prove." priority/></Link><nav><a className="nav-link" href="#workflow">{t.nav.overview}</a><a className="nav-link" href="#intelligence">{t.nav.intelligence}</a><a className="nav-link" href="#trust">{t.nav.trust}</a><LanguageMenu current={locale}/><a className="app-login" href={APP_URL} target="_blank" rel="noreferrer"><span className="app-login-dot"/>{t.appLogin}<span aria-hidden="true">↗</span></a><a className="button small demo-nav" href="#pilot">{t.walkthrough}</a></nav></header>
  <main>
    <section className="locale-hero" id="overview"><video autoPlay muted loop playsInline preload="metadata" poster="/qanri/editorial/field-operations-hero.png" aria-hidden="true"><source src="/qanri/editorial/envato/qanri-field-operations-hero.mp4" type="video/mp4"/></video><div className="locale-hero-copy"><p className="micro-label">{t.hero.eyebrow}</p><h1>{t.hero.title}</h1><p>{t.hero.body}</p><div className="hero-cta-row"><a className="button" href="#pilot">{t.walkthrough}</a><a className="quiet-link" href="#workflow">{t.hero.explore} <span>↗</span></a></div><ul>{t.hero.proof.map(item=><li key={item}>{item}</li>)}</ul></div><div className="locale-hero-visual"><div className="ops-window localized-ops"><div className="ops-bar"><span><i/><i/><i/></span><b>QANRI / OPERATING PICTURE</b><em>LIVE MODEL</em></div><div className="ops-body"><aside><div className="ops-symbol"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt=""/></div>{t.flow.steps.slice(0,5).map((x,i)=><span className={i===0?"selected":""} key={x[0]}>{x[0]}</span>)}</aside><div className="ops-main"><header><div><small>QANRI · LIVE</small><h2>{t.ai.managerRole}</h2></div><button>{t.flow.steps[0][0]}</button></header><div className="ops-stats"><article><span>FIELD WORK</span><b>24</b><small>{t.flow.steps[1][0]}</small></article><article><span>PROOF</span><b>11</b><small>{t.flow.steps[3][0]}</small></article><article><span>ACTION</span><b>04</b><small>{t.flow.steps[4][0]}</small></article></div><div className="ops-grid"><div className="ops-activity"><div className="panel-title"><b>{t.flow.title}</b><span>LIVE</span></div>{p.chain.slice(1,5).map(([a,b],i)=><div className="activity-row" key={a}><i className={`tone-${i}`}/><span><b>{a}</b><small>{b}</small></span><time>{["10:24","10:08","09:51","09:37"][i]}</time></div>)}</div><div className="ops-attention"><div className="panel-title"><b>{t.ai.managerRole}</b><span>4</span></div><div className="attention-card"><small>ASK QANRI</small><b>{t.ai.managerQuestion}</b><p>{t.ai.managerAnswer}</p></div></div></div></div></div></div></div></section>

    <section className="locale-model" aria-label="Know Move Prove"><article><b>KNOW.</b><p>{t.model.know}</p></article><article><b>MOVE.</b><p>{t.model.move}</p></article><article><b>PROVE.</b><p>{t.model.prove}</p></article></section>

    <section className="intelligence-bridge locale-bridge"><p className="micro-label dark">{p.bridge.eyebrow}</p><h2>{p.bridge.title}</h2><div className="bridge-flow">{p.bridge.steps.map(([title,body],i)=><span className="bridge-item-wrap" key={title}><article><span>{String(i+1).padStart(2,"0")}</span><b>{title}</b><p>{body}</p></article>{i<2&&<i>→</i>}</span>)}</div><strong>{p.bridge.close}</strong></section>

    <section className="locale-flow" id="workflow"><div><p className="micro-label dark">{t.flow.eyebrow}</p><h2>{t.flow.title}</h2><p>{t.flow.body}</p></div><ol>{p.chain.map(([title,body],index)=><li key={title}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></section>

    <section className="locale-questions"><div><p className="micro-label dark">{d.questions.eyebrow}</p><h2>{d.questions.title}</h2><p>{d.questions.body}</p></div><ol>{questions.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span><strong>{item}</strong></li>)}</ol></section>

    <LocalizedProductTour locale={locale}/>

    <section className="locale-evidence-rich" id="evidence"><div className="evidence-copy"><p className="micro-label dark">{d.evidence.eyebrow}</p><h2>{d.evidence.title}</h2><p>{d.evidence.body}</p><div className="evidence-photo"><Image src="/qanri/editorial/envato/qanri-field-evidence.jpg" fill sizes="(max-width:900px) 100vw,50vw" alt=""/></div><a className="dark-link" href="#evidence-record">{p.links.evidence} →</a></div><div className="submission-stack localized-submissions" id="evidence-record"><div className="submission old"><header><span>{p.evidence.old}</span><b>{p.evidence.retained}</b></header><h3>{p.evidence.task}</h3><p>“{p.evidence.oldNote}”</p><div className="submission-meta"><span>{p.evidence.person}</span><span>09:42</span><span>{p.evidence.photo}</span></div></div><div className="review-line"><span>{p.evidence.correction}</span><p>{p.evidence.correctionBody}</p></div><div className="submission current"><header><span>{p.evidence.current}</span><b>{p.evidence.ready}</b></header><h3>{p.evidence.newTitle}</h3><p>{p.evidence.newNote}</p><div className="submission-meta"><span>{p.evidence.person}</span><span>10:24</span><span>{p.evidence.photo}</span></div></div></div></section>

    <section className="locale-comparison"><div><p className="micro-label">{d.comparison.eyebrow}</p><h2>{d.comparison.title}</h2></div><div className="comparison-table"><header><span>{d.comparison.before}</span><span>{d.comparison.after}</span></header>{comparisons.map(([before,after])=><article key={before}><p>{before}</p><p>{after}</p></article>)}</div></section>

    <section className="locale-brand-story" id="brand-story"><div className="locale-brand-intro"><p className="micro-label">{t.brand.eyebrow}</p><h2>{t.brand.title}</h2><p>{t.brand.body}</p><a className="quiet-link" href="#brand-story">{p.links.story} <span>↗</span></a></div><div className="locale-principles">{t.brand.principles.map(([letter,title,body])=><article key={letter}><span>{letter}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>

    <section className="locale-offline-rich" id="offline"><div className="offline-visual"><div className="signal-ring r1"/><div className="signal-ring r2"/><div className="signal-ring r3"/><div className="offline-device"><span>OFFLINE</span><b>{d.offline.title}</b><p>{d.offline.body}</p><div><i/><small>LOCAL QUEUE</small></div></div></div><div><p className="micro-label">{d.offline.eyebrow}</p><h2>{d.offline.title}</h2><p>{d.offline.body}</p><ul>{d.offline.items.map(item=><li key={item}>{item}</li>)}</ul><a className="quiet-link" href="#offline">{p.links.offline} <span>↗</span></a></div></section>

    <section className="locale-roles-rich"><div><p className="micro-label dark">{d.roles.eyebrow}</p><h2>{d.roles.title}</h2><p>{d.roles.body}</p></div><div className="role-columns localized-role-columns">{d.roles.items.map(([title,mode],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><ul>{p.roleBullets[index].map(x=><li key={x}>{x}</li>)}</ul><small>{mode}</small></article>)}</div></section>

    <section className="locale-ai" id="intelligence"><div className="locale-ai-intro"><p className="micro-label">{t.ai.eyebrow}</p><h2>{t.ai.title}</h2><p>{t.ai.body}</p><div className="intelligence-guardrails"><span>COMPANY KNOWLEDGE</span><span>LIVE CONTEXT</span><span>TRACEABLE ANSWERS</span></div></div><div className="locale-ai-orbit"><div className="orbit-ring orbit-one"/><div className="orbit-ring orbit-two"/><div className="orbit-core"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt="QANRI"/><b>ASK QANRI</b><span>{localeNames[locale]}</span></div></div><div className="locale-ai-cards three">{[[t.ai.fieldRole,t.ai.fieldQuestion,t.ai.fieldAnswer,"IN THE FIELD"],[p.aiThird.role,p.aiThird.question,p.aiThird.answer,p.aiThird.label],[t.ai.managerRole,t.ai.managerQuestion,t.ai.managerAnswer,"ACROSS OPERATIONS"]].map(([role,question,answer,label],i)=><article key={question}><span>{String(i+1).padStart(2,"0")}</span><small className="scenario-label">{label}</small><p>{role}</p><h3>“{question}”</h3><small>{answer}</small></article>)}</div><strong>{t.ai.close}</strong><a className="quiet-link ai-link" href="#intelligence">{p.links.ai} <span>↗</span></a></section>

    <section className="locale-security-rich" id="trust"><div><p className="micro-label">{p.trust.eyebrow}</p><h2>{p.trust.title}</h2><p>{p.trust.body}</p></div><div className="security-grid">{p.trust.items.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="locale-languages" id="languages"><div><p className="micro-label dark">{t.language.eyebrow}</p><h2>{t.language.title}</h2><p>{t.language.body}</p></div><div className="language-status-list">{productLanguages.map(item=><article key={item.locale}><b lang={item.locale}>{localeNames[item.locale]}</b><span className={item.status}>{item.status==="available"?t.language.available:t.language.preparing}</span></article>)}</div><p className="language-note">{t.language.note}</p></section>

    <section className="locale-pilot-rich" id="pilot"><div><p className="micro-label">{d.pilot.eyebrow}</p><h2>{d.pilot.title}</h2><p>{d.pilot.body}</p></div><ol>{d.pilot.items.map(([number,title],i)=><li key={number}><span>{number}</span><div><strong>{title}</strong><p>{p.pilotBodies[i]}</p></div></li>)}</ol></section>

    <section className="final-section locale-final"><div className="final-brand"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt="QANRI"/><span>QANRI</span></div><p className="micro-label">{t.final.eyebrow}</p><h2>{t.final.title}</h2><p>{t.final.body}</p><a className="button" href="#pilot">{t.final.button}</a></section>
  </main>
  <footer className="locale-footer"><div className="footer-brand"><Image src="/qanri/QANRI_Web_Lockup_Transparent.png" width={1141} height={304} alt="QANRI"/><p>{t.footer}</p><strong>A COREX ROBOTICS PRODUCT</strong></div><LanguageMenu current={locale}/><p className="fine">QANRI is developed by CoreX Robotics Services LLC.<br/>© {new Date().getFullYear()} CoreX Robotics Services LLC. New Jersey, USA.</p></footer>
</div>}
