import Image from "next/image";
import Link from "next/link";
import { ProductTour } from "./product-tour";
import { Shell } from "./site";

const questions=["What was completed today?","What is still blocked?","Who owns the next action?","What needs verification?","Where is the proof?"];

export default function Home(){return <Shell><main className="product-home">
  <section className="product-hero">
    <div className="product-hero-copy"><p className="micro-label">OPERATIONAL INTELLIGENCE FOR FIELD WORK</p><h1>Know what happened.<br/>Know what happens next.</h1><p>QANRI connects field work, assignments, evidence, blockers and verification into one trusted operating picture—without turning the field into a data-entry department.</p><div className="hero-cta-row"><Link className="button" href="/demo">See QANRI at work</Link><Link className="quiet-link" href="/platform">Explore the platform <span>↗</span></Link></div><div className="hero-note"><b>PRIVATE DEMO / PILOT</b><span>Built for specialty contractors, installation and commissioning teams.</span></div></div>
    <div className="product-hero-ui"><div className="ops-window"><div className="ops-bar"><span><i/><i/><i/></span><b>QANRI / OPERATING PICTURE</b><em>LIVE MODEL</em></div><div className="ops-body"><aside><div className="ops-symbol"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt=""/></div>{["Today","Projects","People","Evidence","Blockers","Handover"].map((x,i)=><span className={i===0?"selected":""} key={x}>{x}</span>)}</aside><div className="ops-main"><header><div><small>MONDAY · AUGUST 10</small><h2>Good morning, Operations.</h2></div><button>+ Assign work</button></header><div className="ops-stats"><article><span>FIELD WORK</span><b>24</b><small>active assignments</small></article><article><span>PROOF RECEIVED</span><b>11</b><small>today</small></article><article><span>NEEDS ACTION</span><b>04</b><small>reviews + blockers</small></article></div><div className="ops-grid"><div className="ops-activity"><div className="panel-title"><b>Operational pulse</b><span>View all</span></div>{[["Evidence submitted","Rail connection check","10:24"],["Rework requested","Door mechanism test","10:08"],["Blocker opened","Electrical panel access","09:51"],["Task reassigned","Commissioning checklist","09:37"]].map(([a,b,c],i)=><div className="activity-row" key={a}><i className={`tone-${i}`}/><span><b>{a}</b><small>{b}</small></span><time>{c}</time></div>)}</div><div className="ops-attention"><div className="panel-title"><b>Needs attention</b><span>4 items</span></div><div className="attention-card"><small>BLOCKER</small><b>Electrical panel access</b><p>Owner: Project Admin</p><span>Open blocker →</span></div><div className="attention-card"><small>REVIEW</small><b>Rail connection check</b><p>Submission #1 · 1 photo</p><span>Review evidence →</span></div></div></div></div></div></div><p className="ui-disclaimer">Illustrative interface based on the verified QANRI workflow—not customer or production data.</p></div>
  </section>

  <section className="brand-strip"><span>KNOW.</span><i/> <span>MOVE.</span><i/> <span>PROVE.</span><p>Never chase the operation again.</p></section>

  <section className="problem-section"><div className="problem-lead"><p className="micro-label dark">THE OPERATION IS MOVING</p><h2>The truth should not require a phone call.</h2><p>Work happens in the field. Proof sits in camera rolls. Delays live in messages. Rework is remembered by the person who was there. QANRI turns those fragments into an operating record.</p></div><div className="question-stack">{questions.map((q,i)=><div key={q}><span>{String(i+1).padStart(2,"0")}</span><b>{q}</b></div>)}</div></section>

  <section className="tour-section"><div className="section-heading"><p className="micro-label">THE PRODUCT IN MOTION</p><h2>Follow one workday from assignment to proof.</h2><p>The product story is not a feature wall. It is one connected operating chain.</p></div><ProductTour/></section>

  <section className="evidence-section"><div className="evidence-copy"><p className="micro-label dark">EVIDENCE & VERIFICATION</p><h2>Done is a record.<br/>Not a checkbox.</h2><p>A completed task carries the note, evidence, person, time and verification decision that made it real.</p><Link className="dark-link" href="/platform/evidence-verification">Explore evidence and verification →</Link></div><div className="submission-stack"><div className="submission old"><header><span>SUBMISSION #1</span><b>PRESERVED</b></header><h3>Rail connection check</h3><p>“Torque checked. Final alignment photo attached.”</p><div className="submission-meta"><span>Alex Morgan</span><span>09:42</span><span>1 photo</span></div></div><div className="review-line"><span>REWORK REQUESTED</span><p>Foreman asks for a corrected final view. The original submission remains intact.</p></div><div className="submission current"><header><span>SUBMISSION #2</span><b>AWAITING REVIEW</b></header><h3>Corrected evidence received</h3><p>New note and new evidence. Nothing overwritten.</p><div className="submission-meta"><span>Alex Morgan</span><span>10:24</span><span>1 photo</span></div></div></div></section>

  <section className="offline-section"><div className="offline-visual"><div className="signal-ring r1"/><div className="signal-ring r2"/><div className="signal-ring r3"/><div className="offline-device"><span>OFFLINE</span><b>Work saved on this device</b><p>3 actions and 2 evidence files are ready to synchronize.</p><div><i/><small>Durable local queue</small></div></div></div><div className="offline-copy"><p className="micro-label">OFFLINE-FIRST FIELD EXECUTION</p><h2>The field doesn’t wait for Wi-Fi.</h2><p>Core field actions are designed to persist locally, survive app restarts and synchronize when a useful connection returns.</p><ul><li>Evidence remains tied to the work</li><li>Reconnect does not become a field task</li><li>Retries are designed not to duplicate accepted events</li></ul><Link className="quiet-link" href="/platform/offline">See how offline works <span>↗</span></Link></div></section>

  <section className="roles-section"><div className="section-heading light-heading"><p className="micro-label dark">ONE OPERATING PICTURE</p><h2>Different responsibilities.<br/>The same operational truth.</h2></div><div className="role-columns"><article><span>01</span><h3>Worker</h3><p>Know today’s work. Capture the proof. Submit and move.</p><small>FOCUSED EXECUTION</small></article><article><span>02</span><h3>Foreman</h3><p>See the crew. Assign work. Review evidence. Route rework.</p><small>VISIBLE OWNERSHIP</small></article><article><span>03</span><h3>Operations</h3><p>Build templates. Follow blockers, activity and handover without chasing.</p><small>TRUSTED PICTURE</small></article></div></section>

  <section className="ai-section"><div className="ai-mark"><span>Q</span><div>AUTHORIZED SOURCES<br/>CITED ENTITIES<br/>ROLE-AWARE ACCESS</div></div><div className="ai-copy"><p className="micro-label">ASK QANRI</p><h2>Ask the operation.<br/>Get a sourced answer.</h2><p>QANRI AI is an optional interface over the operating record. It is designed to use the same authorization boundaries as the platform and cite the sources behind an answer.</p><blockquote>AI should not invent the operation.<br/><b>It should read the operation.</b></blockquote><Link className="quiet-link" href="/platform/ask-qanri">Meet Ask QANRI <span>↗</span></Link></div></section>

  <section className="trust-section"><div><p className="micro-label dark">TRUST ARCHITECTURE</p><h2>Serious operations need serious boundaries.</h2><p>QANRI’s trust story is built from verified product behavior—not borrowed badges.</p></div><div className="trust-table">{[["Company scope","Data remains scoped by company identity."],["Project authority","Foreman access follows explicit project grants."],["Private evidence","Authorized, time-limited application access."],["Audit history","Append-only operational events preserve what happened."],["Offline protection","Encrypted local queue on supported native builds."],["Operational AI","Authorization-aware tools; no unrestricted database access."]].map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>

  <section className="final-section"><div className="final-brand"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt="QANRI symbol"/><span>QANRI</span></div><p className="micro-label">PRIVATE DEMO / PILOT ROLLOUT</p><h2>See your own operation<br/>in the flow.</h2><p>Tell us how your field work runs today. We will show you where QANRI fits—and where it deliberately does not.</p><Link className="button" href="/demo">Request a private demo</Link><small>QANRI? <b>And you?</b></small></section>
</main></Shell>}
