import Image from "next/image";
import Link from "next/link";
import { ProductTour } from "./product-tour";
import { Shell } from "./site";

const questions=["What was completed today?","What is still blocked?","Who owns the next action?","What needs verification?","Where is the proof?"];
const operatingChain=[
  ["01","Assign","Define the work, owner and required evidence."],
  ["02","Execute","The worker sees the assignment and records progress in the field."],
  ["03","Submit","A completion note and supporting evidence return with the work."],
  ["04","Review","The foreman accepts the submission or requests a correction."],
  ["05","Preserve","Earlier submissions, decisions and responsibility remain visible."],
  ["06","Act","Operations sees blockers, pending reviews and the next owner."],
];
const comparison=[
  ["Photos sit in personal camera rolls.","Evidence stays connected to the assignment and submission."],
  ["Blockers disappear into calls and messages.","The reason, status and next owner remain visible."],
  ["Completed is difficult to verify later.","Completion arrives as a reviewable record with context."],
  ["A correction replaces the earlier story.","Each submission remains available as a separate version."],
  ["Poor connectivity postpones field reporting.","Core field actions persist locally and synchronize later."],
];

export default function Home(){return <Shell><main className="product-home">
  <section className="product-hero">
    <video className="hero-field-video" autoPlay muted loop playsInline preload="metadata" poster="/qanri/editorial/field-operations-hero.png" aria-hidden="true"><source src="/qanri/editorial/envato/qanri-field-operations-hero.mp4" type="video/mp4" /></video>
    <div className="product-hero-copy"><p className="micro-label">FIELD OPERATIONS SOFTWARE</p><h1>Assign the work.<br/>Keep the proof.</h1><p>QANRI connects assignments, field updates, evidence, review, rework and blockers in one operating record.</p><div className="hero-cta-row"><Link className="button" href="/demo">Walk through one workflow</Link><a className="quiet-link" href="#workflow">See the operating chain <span>↓</span></a></div><ul className="hero-proof"><li>Designed for poor connectivity</li><li>Evidence remains tied to the work</li><li>Review history stays visible</li></ul><div className="hero-note"><b>PRIVATE PILOT CONVERSATIONS</b><span>For field organizations that need a clearer record of execution.</span></div></div>
    <div className="product-hero-ui"><div className="ops-window"><div className="ops-bar"><span><i/><i/><i/></span><b>QANRI / OPERATING PICTURE</b><em>LIVE MODEL</em></div><div className="ops-body"><aside><div className="ops-symbol"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt=""/></div>{["Today","Projects","People","Evidence","Blockers","Handover"].map((x,i)=><span className={i===0?"selected":""} key={x}>{x}</span>)}</aside><div className="ops-main"><header><div><small>MONDAY · AUGUST 10</small><h2>Good morning, Operations.</h2></div><button>+ Assign work</button></header><div className="ops-stats"><article><span>FIELD WORK</span><b>24</b><small>active assignments</small></article><article><span>PROOF RECEIVED</span><b>11</b><small>today</small></article><article><span>NEEDS ACTION</span><b>04</b><small>reviews + blockers</small></article></div><div className="ops-grid"><div className="ops-activity"><div className="panel-title"><b>Operational pulse</b><span>View all</span></div>{[["Evidence submitted","Rail connection check","10:24"],["Rework requested","Door mechanism test","10:08"],["Blocker opened","Electrical panel access","09:51"],["Task reassigned","Commissioning checklist","09:37"]].map(([a,b,c],i)=><div className="activity-row" key={a}><i className={`tone-${i}`}/><span><b>{a}</b><small>{b}</small></span><time>{c}</time></div>)}</div><div className="ops-attention"><div className="panel-title"><b>Needs attention</b><span>4 items</span></div><div className="attention-card"><small>BLOCKER</small><b>Electrical panel access</b><p>Owner: Project Admin</p><span>Open blocker →</span></div><div className="attention-card"><small>REVIEW</small><b>Rail connection check</b><p>Submission #1 · 1 photo</p><span>Review evidence →</span></div></div></div></div></div></div><p className="ui-disclaimer">Illustrative interface based on the verified QANRI workflow—not customer or production data.</p></div>
  </section>

  <section className="brand-strip"><span>KNOW.</span><i/> <span>MOVE.</span><i/> <span>PROVE.</span><p>A clear record of work in progress.</p></section>

  <section className="workflow-story" id="workflow"><div className="workflow-intro"><p className="micro-label dark">ONE JOB, END TO END</p><h2>Follow the work, not a feature list.</h2><p>QANRI is built around a connected sequence. Every step adds context to the same operational record.</p></div><ol>{operatingChain.map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>

  <section className="problem-section"><div className="problem-lead"><p className="micro-label dark">WHAT MANAGEMENT NEEDS TO KNOW</p><h2>Field updates should be easy to find.</h2><p>Photos end up on personal phones. Delays are discussed in messages. Completed work is difficult to verify later. QANRI keeps the assignment, update, evidence and review together.</p></div><div className="question-stack">{questions.map((q,i)=><div key={q}><span>{String(i+1).padStart(2,"0")}</span><b>{q}</b></div>)}</div></section>

  <section className="tour-section"><div className="section-heading"><p className="micro-label">THE PRODUCT IN MOTION</p><h2>Follow one workday from assignment to proof.</h2><p>The product story is not a feature wall. It is one connected operating chain.</p></div><ProductTour/></section>

  <section className="evidence-section"><div className="evidence-copy"><p className="micro-label dark">EVIDENCE AND REVIEW</p><h2>A completion should come with context.</h2><p>Each update can include the person, time, note and supporting evidence. If work is returned, the earlier submission remains available.</p><div className="evidence-photo"><Image src="/qanri/editorial/envato/qanri-field-evidence.jpg" width={1536} height={1024} alt="Field technician recording work on a digital tablet"/></div><Link className="dark-link" href="/platform/evidence-verification">See the evidence workflow →</Link></div><div className="submission-stack"><div className="submission old"><header><span>SUBMISSION 01</span><b>RETAINED</b></header><h3>Connection inspection</h3><p>“Torque checked. Final installation photo attached.”</p><div className="submission-meta"><span>Alex Morgan</span><span>09:42</span><span>1 photo</span></div></div><div className="review-line"><span>CORRECTION REQUESTED</span><p>The foreman asks for a clearer final view. The first submission stays in the record.</p></div><div className="submission current"><header><span>SUBMISSION 02</span><b>READY FOR REVIEW</b></header><h3>Updated evidence received</h3><p>A new note and a new photo are ready for review.</p><div className="submission-meta"><span>Alex Morgan</span><span>10:24</span><span>1 photo</span></div></div></div></section>

  <section className="before-after"><div className="before-after-head"><p className="micro-label dark">THE OPERATING DIFFERENCE</p><h2>Replace chasing with a record.</h2><p>This is the behavior QANRI is designed to change.</p></div><div className="comparison-table"><div className="comparison-labels"><b>WITHOUT A CONNECTED RECORD</b><b>WITH QANRI</b></div>{comparison.map(([before,after],i)=><div className="comparison-row" key={before}><span>{String(i+1).padStart(2,"0")}</span><p>{before}</p><p>{after}</p></div>)}</div></section>

  <section className="offline-section"><div className="offline-visual"><div className="signal-ring r1"/><div className="signal-ring r2"/><div className="signal-ring r3"/><div className="offline-device"><span>OFFLINE</span><b>Work saved on this device</b><p>3 actions and 2 evidence files are ready to synchronize.</p><div><i/><small>Durable local queue</small></div></div></div><div className="offline-copy"><p className="micro-label">OFFLINE-FIRST FIELD EXECUTION</p><h2>The field doesn’t wait for Wi-Fi.</h2><p>Core field actions are designed to persist locally, survive app restarts and synchronize when a useful connection returns.</p><ul><li>Evidence remains tied to the work</li><li>Reconnect does not become a field task</li><li>Retries are designed not to duplicate accepted events</li></ul><Link className="quiet-link" href="/platform/offline">See how offline works <span>↗</span></Link></div></section>

  <section className="roles-section"><div className="section-heading light-heading"><p className="micro-label dark">ONE OPERATING PICTURE</p><h2>Different decisions.<br/>The same operational truth.</h2></div><div className="role-columns"><article><span>01</span><h3>Worker</h3><ul><li>See the work assigned for today</li><li>Record progress, notes and evidence</li><li>Continue through weak connectivity</li><li>Submit without rebuilding the context</li></ul><small>EXECUTE AND REPORT</small></article><article><span>02</span><h3>Foreman</h3><ul><li>Assign work to the crew</li><li>Review the evidence returned</li><li>Request correction without deleting history</li><li>Route blockers to the next owner</li></ul><small>REVIEW AND DIRECT</small></article><article><span>03</span><h3>Operations</h3><ul><li>See pending work across projects</li><li>Find blockers and unresolved reviews</li><li>Understand who owns the next action</li><li>Preserve the record for handover</li></ul><small>SEE AND ACT</small></article></div></section>

  <section className="ai-section"><div className="ai-mark"><span>Q</span><div>AUTHORIZED SOURCES<br/>CITED ENTITIES<br/>ROLE-AWARE ACCESS</div></div><div className="ai-copy"><p className="micro-label">ASK QANRI</p><h2>Ask the operation.<br/>Get a sourced answer.</h2><p>QANRI AI is an optional interface over the operating record. It is designed to use the same authorization boundaries as the platform and cite the sources behind an answer.</p><blockquote>AI should not invent the operation.<br/><b>It should read the operation.</b></blockquote><Link className="quiet-link" href="/platform/ask-qanri">Meet Ask QANRI <span>↗</span></Link></div></section>

  <section className="trust-section"><div><p className="micro-label dark">ACCESS AND HISTORY</p><h2>People should see the work they are responsible for.</h2><p>Our security statements describe current product behavior. We do not display certifications or integration claims that have not been verified.</p></div><div className="trust-table">{[["Company scope","Data remains scoped by company identity."],["Project authority","Foreman access follows explicit project grants."],["Private evidence","Authorized, time-limited application access."],["Audit history","Append-only operational events preserve what happened."],["Offline protection","Encrypted local queue on supported native builds."],["Operational AI","Authorization-aware tools with no unrestricted database access."]].map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>

  <section className="pilot-section"><div><p className="micro-label">CONTROLLED PILOT</p><h2>Test one real workflow before making a broad commitment.</h2><p>A pilot conversation begins with the way your team assigns, reports and reviews work today. Together, we identify the workflow, the operating boundaries and the evidence that would make the pilot useful.</p></div><ol><li><span>01</span><b>Map the current workflow</b><p>Show where assignments, updates, evidence and decisions live today.</p></li><li><span>02</span><b>Define the pilot boundary</b><p>Select a practical project, crew or repeatable work package.</p></li><li><span>03</span><b>Agree on useful signals</b><p>Choose observable measures such as missing evidence, review delay or time spent chasing updates.</p></li><li><span>04</span><b>Review the result</b><p>Decide from the operating record whether QANRI is a fit.</p></li></ol></section>

  <section className="final-section"><div className="final-brand"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt="QANRI symbol"/><span>QANRI</span></div><p className="micro-label">PRIVATE PRODUCT WALKTHROUGH</p><h2>Bring us one real workflow.</h2><p>Show us how work is assigned, reported and reviewed today. We will show you what the same process looks like in QANRI.</p><Link className="button" href="/demo">Book a walkthrough</Link></section>
</main></Shell>}
