import Image from "next/image";
import Link from "next/link";
import { ProductTour } from "./product-tour";
import { Shell } from "./site";

const questions=["What was completed today?","What is still blocked?","Who owns the next action?","What needs verification?","Where is the proof?"];
const operatingChain=[
  ["01","Assign","Define the work, owner and required evidence."],
  ["02","Execute","The worker sees the assignment and records progress in the field."],
  ["03","Submit","A completion note and supporting evidence return with the work."],
  ["04","Review","The foreman accepts the submission or requests a correction."],
  ["05","Preserve","Earlier submissions, decisions and responsibility remain visible."],
  ["06","Act","Operations sees blockers, pending reviews and the next owner."],
];
const comparison=[
  ["Photos sit in personal camera rolls.","Evidence stays connected to the assignment and submission."],
  ["Blockers disappear into calls and messages.","The reason, status and next owner remain visible."],
  ["Completed is difficult to verify later.","Completion arrives as a reviewable record with context."],
  ["A correction replaces the earlier story.","Each submission remains available as a separate version."],
  ["Poor connectivity postpones field reporting.","Core field actions persist locally and synchronize later."],
];
const brandPrinciples=[
  ["Q","Quality","Make the standard of work visible, measurable and ready to improve."],
  ["A","Accountability","Keep responsibility, time and evidence connected to the work."],
  ["N","Navigation","Turn the operating record into the right next action."],
  ["R","Reliability","Preserve field reality with its versions, decisions and history intact."],
  ["I","Intelligence","Transform operational activity into knowledge the company can use."],
];
const intelligenceRoles=[
  ["01","IN THE FIELD","A technician asks","How should this assembly be completed?","QANRI brings the relevant company procedure, project context and recorded work into one guided answer."],
  ["02","WHEN WORK STOPS","A team member asks","What should I check before escalating this fault?","QANRI helps the person investigate with the approved knowledge available to their company and keeps the issue connected to the work."],
  ["03","ACROSS OPERATIONS","A manager asks","What is at risk right now, and who owns the next action?","QANRI reads the live operating picture and returns an answer grounded in assignments, blockers, evidence and review status."],
];

export default function Home(){return <Shell><main className="product-home">
  <section className="product-hero">
    <video className="hero-field-video" autoPlay muted loop playsInline preload="metadata" poster="/qanri/editorial/field-operations-hero.png" aria-hidden="true"><source src="/qanri/editorial/envato/qanri-field-operations-hero.mp4" type="video/mp4" /></video>
    <div className="product-hero-copy"><p className="micro-label">OPERATIONAL INTELLIGENCE PLATFORM</p><h1>The intelligence between work and proof.</h1><p>QANRI turns real operational activity into knowledge, knowledge into decisive action, and completed work into verifiable proof.</p><div className="hero-cta-row"><Link className="button" href="/demo">Book a walkthrough</Link><Link className="quiet-link" href="/platform">Explore the platform <span>↗</span></Link></div><ul className="hero-proof"><li>People and projects connected</li><li>Evidence remains tied to the work</li><li>Responsibility drives the next action</li></ul><div className="hero-note"><b>BUILT FIRST FOR FIELD EXECUTION</b><span>Start in the field. Build the operational record. Direct the entire operation with confidence.</span></div></div>
    <div className="product-hero-ui"><div className="ops-window"><div className="ops-bar"><span><i/><i/><i/></span><b>QANRI / OPERATING PICTURE</b><em>LIVE MODEL</em></div><div className="ops-body"><aside><div className="ops-symbol"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt=""/></div>{["Today","Projects","People","Evidence","Blockers","Handover"].map((x,i)=><span className={i===0?"selected":""} key={x}>{x}</span>)}</aside><div className="ops-main"><header><div><small>MONDAY · AUGUST 10</small><h2>Good morning, Operations.</h2></div><button>+ Assign work</button></header><div className="ops-stats"><article><span>FIELD WORK</span><b>24</b><small>active assignments</small></article><article><span>PROOF RECEIVED</span><b>11</b><small>today</small></article><article><span>NEEDS ACTION</span><b>04</b><small>reviews + blockers</small></article></div><div className="ops-grid"><div className="ops-activity"><div className="panel-title"><b>Operational pulse</b><span>View all</span></div>{[["Evidence submitted","Rail connection check","10:24"],["Rework requested","Door mechanism test","10:08"],["Blocker opened","Electrical panel access","09:51"],["Task reassigned","Commissioning checklist","09:37"]].map(([a,b,c],i)=><div className="activity-row" key={a}><i className={`tone-${i}`}/><span><b>{a}</b><small>{b}</small></span><time>{c}</time></div>)}</div><div className="ops-attention"><div className="panel-title"><b>Needs attention</b><span>4 items</span></div><div className="attention-card"><small>BLOCKER</small><b>Electrical panel access</b><p>Owner: Project Admin</p><span>Open blocker →</span></div><div className="attention-card"><small>REVIEW</small><b>Rail connection check</b><p>Submission #1 · 1 photo</p><span>Review evidence →</span></div></div></div></div></div></div><p className="ui-disclaimer">Illustrative interface based on the verified QANRI workflow. Not customer or production data.</p></div>
  </section>

  <section className="brand-model" aria-label="Know Move Prove operating model"><article><b>KNOW.</b><p>See the operation as it actually happened.</p></article><article><b>MOVE.</b><p>Direct the right person, decision and next action.</p></article><article><b>PROVE.</b><p>Verify the work through ownership, time, history and evidence.</p></article></section>

  <section className="intelligence-bridge"><p className="micro-label dark">FROM EXECUTION TO INTELLIGENCE</p><h2>Start with the work.<br/>Build the truth.<br/>Direct the operation.</h2><div className="bridge-flow"><article><span>01</span><b>Field execution</b><p>Assignments, progress, blockers and evidence enter the system where the work happens.</p></article><i>→</i><article><span>02</span><b>Trusted operational record</b><p>Responsibility, time, review and change history stay connected.</p></article><i>→</i><article><span>03</span><b>Operational intelligence</b><p>The company can understand what happened, decide what comes next and improve how work moves.</p></article></div><strong>QANRI does not merely track the operation. It makes the operation understandable, accountable and ready to improve.</strong></section>

  <section className="workflow-story" id="workflow"><div className="workflow-intro"><p className="micro-label dark">ONE JOB, END TO END</p><h2>Follow the work, not a feature list.</h2><p>QANRI is built around a connected sequence. Every step adds context to the same operational record.</p></div><ol>{operatingChain.map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>

  <section className="problem-section"><div className="problem-lead"><p className="micro-label dark">WHAT MANAGEMENT NEEDS TO KNOW</p><h2>Field updates should be easy to find.</h2><p>Photos end up on personal phones. Delays are discussed in messages. Completed work is difficult to verify later. QANRI keeps the assignment, update, evidence and review together.</p></div><div className="question-stack">{questions.map((q,i)=><div key={q}><span>{String(i+1).padStart(2,"0")}</span><b>{q}</b></div>)}</div></section>

  <section className="tour-section"><div className="section-heading"><p className="micro-label">THE PRODUCT IN MOTION</p><h2>Follow one workday from assignment to proof.</h2><p>The product story is not a feature wall. It is one connected operating chain.</p></div><ProductTour/></section>

  <section className="evidence-section"><div className="evidence-copy"><p className="micro-label dark">EVIDENCE AND REVIEW</p><h2>A completion should come with context.</h2><p>Each update can include the person, time, note and supporting evidence. If work is returned, the earlier submission remains available.</p><div className="evidence-photo"><Image src="/qanri/editorial/envato/qanri-field-evidence.jpg" width={1536} height={1024} alt="Field technician recording work on a digital tablet"/></div><Link className="dark-link" href="/platform/evidence-verification">See the evidence workflow →</Link></div><div className="submission-stack"><div className="submission old"><header><span>SUBMISSION 01</span><b>RETAINED</b></header><h3>Connection inspection</h3><p>“Torque checked. Final installation photo attached.”</p><div className="submission-meta"><span>Alex Morgan</span><span>09:42</span><span>1 photo</span></div></div><div className="review-line"><span>CORRECTION REQUESTED</span><p>The foreman asks for a clearer final view. The first submission stays in the record.</p></div><div className="submission current"><header><span>SUBMISSION 02</span><b>READY FOR REVIEW</b></header><h3>Updated evidence received</h3><p>A new note and a new photo are ready for review.</p><div className="submission-meta"><span>Alex Morgan</span><span>10:24</span><span>1 photo</span></div></div></div></section>

  <section className="before-after"><div className="before-after-head"><p className="micro-label dark">THE OPERATING DIFFERENCE</p><h2>Replace chasing with a record.</h2><p>This is the behavior QANRI is designed to change.</p></div><div className="comparison-table"><div className="comparison-labels"><b>WITHOUT A CONNECTED RECORD</b><b>WITH QANRI</b></div>{comparison.map(([before,after],i)=><div className="comparison-row" key={before}><span>{String(i+1).padStart(2,"0")}</span><p>{before}</p><p>{after}</p></div>)}</div></section>

  <section className="principles-section"><div className="principles-lead"><p className="micro-label">WHAT QANRI MEANS</p><h2>The name defines the operating standard.</h2><p className="principles-definition"><strong>QANRI</strong> is formed from <b>Q</b>uality, <b>A</b>ccountability, <b>N</b>avigation, <b>R</b>eliability and <b>I</b>ntelligence.</p><p>These are not decorative brand values. They define how the platform records work, directs action and builds operational intelligence.</p><Link className="quiet-link" href="/why-qanri">Read the QANRI story <span>↗</span></Link></div><div className="principle-list" aria-label="The five principles that form the name QANRI">{brandPrinciples.map(([letter,title,body])=><article key={letter}><span>{letter}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>

  <section className="offline-section"><div className="offline-visual"><div className="signal-ring r1"/><div className="signal-ring r2"/><div className="signal-ring r3"/><div className="offline-device"><span>OFFLINE</span><b>Work saved on this device</b><p>3 actions and 2 evidence files are ready to synchronize.</p><div><i/><small>Durable local queue</small></div></div></div><div className="offline-copy"><p className="micro-label">OFFLINE-FIRST FIELD EXECUTION</p><h2>The field doesn’t wait for Wi-Fi.</h2><p>Core field actions are designed to persist locally, survive app restarts and synchronize when a useful connection returns.</p><ul><li>Evidence remains tied to the work</li><li>Reconnect does not become a field task</li><li>Retries are designed not to duplicate accepted events</li></ul><Link className="quiet-link" href="/platform/offline">See how offline works <span>↗</span></Link></div></section>

  <section className="roles-section"><div className="section-heading light-heading"><p className="micro-label dark">ONE OPERATING PICTURE</p><h2>Different decisions.<br/>The same operational truth.</h2></div><div className="role-columns"><article><span>01</span><h3>Worker</h3><ul><li>See the work assigned for today</li><li>Record progress, notes and evidence</li><li>Continue through weak connectivity</li><li>Submit without rebuilding the context</li></ul><small>EXECUTE AND REPORT</small></article><article><span>02</span><h3>Foreman</h3><ul><li>Assign work to the crew</li><li>Review the evidence returned</li><li>Request correction without deleting history</li><li>Route blockers to the next owner</li></ul><small>REVIEW AND DIRECT</small></article><article><span>03</span><h3>Operations</h3><ul><li>See pending work across projects</li><li>Find blockers and unresolved reviews</li><li>Understand who owns the next action</li><li>Preserve the record for handover</li></ul><small>SEE AND ACT</small></article></div></section>

  <section className="intelligence-section" id="operational-intelligence"><div className="intelligence-intro"><p className="micro-label">A COMPANY-SPECIFIC OPERATIONAL BRAIN</p><h2>Every person can ask.<br/>The operation can answer.</h2><p>QANRI gives the workforce an AI assistant that understands the company context around the work. A technician can ask for guidance where the problem occurs. A manager can ask how the operation is moving. Both begin from the same authorized knowledge and live operational record.</p><div className="intelligence-guardrails"><span>COMPANY KNOWLEDGE</span><span>LIVE OPERATING CONTEXT</span><span>TRACEABLE ANSWERS</span></div></div><div className="intelligence-orbit" aria-label="QANRI connects company knowledge, field work and management decisions"><div className="orbit-ring orbit-one"/><div className="orbit-ring orbit-two"/><div className="orbit-core"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt="QANRI intelligence"/><b>ASK QANRI</b><span>Your company&apos;s operational intelligence</span></div><span className="orbit-node node-knowledge">PROCEDURES</span><span className="orbit-node node-field">FIELD CONTEXT</span><span className="orbit-node node-history">WORK HISTORY</span><span className="orbit-node node-live">LIVE STATUS</span></div><div className="intelligence-scenarios">{intelligenceRoles.map(([n,label,role,question,answer])=><article key={n}><header><span>{n}</span><b>{label}</b></header><p className="scenario-role">{role}</p><h3>“{question}”</h3><p>{answer}</p><small>ANSWERED IN THE CONTEXT OF THE COMPANY AND THE WORK</small></article>)}</div><div className="intelligence-close"><p>One intelligence layer. Different questions. The same operational truth.</p><div><blockquote>QANRI does not give generic answers from outside the operation. It helps each authorized person understand, decide and act from the knowledge their company trusts.</blockquote><Link className="quiet-link" href="/platform/ask-qanri">Explore operational AI <span>↗</span></Link></div></div></section>

  <section className="trust-section"><div><p className="micro-label dark">THE TRUSTED OPERATIONAL RECORD</p><h2>Operational intelligence begins with operational truth.</h2><p>QANRI connects responsibility, time, evidence, review and change history so every important answer can be traced back to the work itself.</p></div><div className="trust-table">{[["Responsibility","Know who performed the work and who owns the next action."],["Time and context","See when it happened and which project and assignment it belonged to."],["Evidence","Keep photos, notes and documents connected to the submission they prove."],["Review history","Preserve every decision, correction and version without rewriting the past."],["Access boundaries","Keep company, project and role authority attached to the record."],["Intelligence","Separate recorded operational fact from AI interpretation."]].map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>

  <section className="pilot-section"><div><p className="micro-label">CONTROLLED PILOT</p><h2>Test one real workflow before making a broad commitment.</h2><p>A pilot conversation begins with the way your team assigns, reports and reviews work today. Together, we identify the workflow, the operating boundaries and the evidence that would make the pilot useful.</p></div><ol><li><span>01</span><b>Map the current workflow</b><p>Show where assignments, updates, evidence and decisions live today.</p></li><li><span>02</span><b>Define the pilot boundary</b><p>Select a practical project, crew or repeatable work package.</p></li><li><span>03</span><b>Agree on useful signals</b><p>Choose observable measures such as missing evidence, review delay or time spent chasing updates.</p></li><li><span>04</span><b>Review the result</b><p>Decide from the operating record whether QANRI is a fit.</p></li></ol></section>

  <section className="final-section"><div className="final-brand"><Image src="/qanri/QANRI_Icon_DarkBackground.png" width={240} height={180} alt="QANRI symbol"/><span>QANRI</span></div><p className="micro-label">A COREX ROBOTICS PRODUCT</p><h2>Bring us one real operation.</h2><p>Show us how work moves today. We will show you how QANRI turns that activity into an operational record your company can trust and act on.</p><Link className="button" href="/demo">Book a walkthrough</Link></section>
</main></Shell>}
