import Image from "next/image";
import Link from "next/link";
import { pages, type PageContent } from "./site-content";
import { APP_LINK_LABEL, APP_URL } from "./site-config";

const nav = [["Platform","/platform"],["Solutions","/solutions"],["Security","/security"],["About","/about"]];

export function Header() { return <header className="nav"><Link className="brand-lockup" href="/" aria-label="QANRI home"><Image src="/qanri/QANRI_Web_Lockup_Transparent.png" width={1141} height={304} alt="QANRI — Know. Move. Prove." priority /></Link><nav>{nav.map(([n,h])=><Link className="nav-link" key={h} href={h}>{n}</Link>)}<a className="app-login" href={APP_URL} target="_blank" rel="noreferrer" aria-label={`${APP_LINK_LABEL} — opens QANRI application in a new tab`}><span className="app-login-dot"/>{APP_LINK_LABEL}<span aria-hidden="true">↗</span></a><Link className="button small demo-nav" href="/demo">See QANRI at work</Link></nav></header> }
export function Footer() { return <footer><div className="footer-brand"><Image src="/qanri/QANRI_Web_Lockup_Transparent.png" width={1141} height={304} alt="QANRI — Know. Move. Prove."/><p>Operational Intelligence for Field Work</p></div><div className="footer-links">{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}<a className="footer-app-link" href={APP_URL} target="_blank" rel="noreferrer">{APP_LINK_LABEL} ↗</a><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><p className="fine">QANRI is a product of CoreX Robotics Services LLC. New Jersey, USA.<br/>© {new Date().getFullYear()} CoreX Robotics Services LLC.</p></footer> }
export function Shell({children}:{children:React.ReactNode}) { return <><Header/>{children}<Footer/></> }

export function ContentPage({content}:{content:PageContent}) { return <Shell><main><section className="page-hero"><p className="eyebrow">{content.eyebrow || "QANRI"}</p><h1>{content.title}</h1><p className="lede">{content.body}</p><div className="page-actions"><Link className="button" href="/demo">See QANRI at work</Link><Link className="ghost-button" href="/platform">Understand the operating model</Link></div></section><section className="section-grid">{content.sections.map((s,i)=><article key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p></article>)}</section><DecisionPanel/><FinalCta/></main></Shell> }
export function RoutePage({slug}:{slug:string}) { return <ContentPage content={pages[slug] || {title:"The operation moved. This page didn't.",body:"The page you requested is not here, but QANRI is.",sections:[]}}/> }
export function FinalCta(){return <section className="final"><p className="eyebrow">KNOW. MOVE. PROVE.</p><h2>Stop carrying the operation in your head.</h2><p>See what happens when projects, crews, evidence and next actions stop living in separate places.</p><div className="final-actions"><Link className="button" href="/demo">Request a private demo</Link><a className="ghost-button" href={APP_URL} target="_blank" rel="noreferrer">Existing customer? {APP_LINK_LABEL} ↗</a></div></section>}
function DecisionPanel(){return <section className="decision-panel"><div className="decision-head"><p className="micro-label dark">EVALUATE THE FIT</p><h2>Focused enough for the field.<br/>Structured enough to trust.</h2><p>QANRI is being introduced through private demos and controlled pilots. The goal is to verify operational fit—not force every company into the same rollout.</p></div><div className="decision-columns"><article><span>HIGH-FIT OPERATION</span><ul><li>Multiple crews or projects</li><li>Evidence and rework matter</li><li>Connectivity is unreliable</li><li>Ownership is hard to see</li><li>Handover repeats across projects</li></ul></article><article><span>DELIBERATE BOUNDARIES</span><ul><li>Not an accounting or payroll system</li><li>Not a BIM or estimating engine</li><li>Not a generic CRM</li><li>Not dependent on AI</li><li>No unverified integrations or certifications</li></ul></article><article><span>PILOT QUESTIONS</span><ul><li>Does the crew understand today’s work?</li><li>Does evidence arrive with less chasing?</li><li>Can foremen verify without losing history?</li><li>Can operations see blockers sooner?</li><li>Does QANRI reduce parallel reporting?</li></ul></article></div></section>}
